---

license_connection: icontrol
license_server: activate.f5.com
wsdl: "{{install_path}} + /roles/bigip_license/files/activate.f5.com-f5wsdl-w-https.xml"


# Contains default values for common BIG-IP related settings
dfl_bigip:
    web_user: "admin"
    web_pass: "admin"
